// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS4nl_HgYwWWnlh1rbQ7-LOT3cKI0tzks',
    appId: '1:151063543585:web:56c12d9bcca46d81940860',
    messagingSenderId: '151063543585',
    projectId: 'kensty-8121f',
    authDomain: 'kensty-8121f.firebaseapp.com',
    storageBucket: 'kensty-8121f.firebasestorage.app',
    measurementId: 'G-75XGK4BKKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq_8vuX-8_AXk2mGBQKG4yqC9AGuP4sw4',
    appId: '1:151063543585:android:a99c47f982a4882d940860',
    messagingSenderId: '151063543585',
    projectId: 'kensty-8121f',
    storageBucket: 'kensty-8121f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu54foPVSTkJQzFkUrBIU8s1MUa6dHNjM',
    appId: '1:151063543585:ios:66d3d91e084c492e940860',
    messagingSenderId: '151063543585',
    projectId: 'kensty-8121f',
    storageBucket: 'kensty-8121f.firebasestorage.app',
    iosBundleId: 'avarewase.org.kensty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu54foPVSTkJQzFkUrBIU8s1MUa6dHNjM',
    appId: '1:151063543585:ios:66d3d91e084c492e940860',
    messagingSenderId: '151063543585',
    projectId: 'kensty-8121f',
    storageBucket: 'kensty-8121f.firebasestorage.app',
    iosBundleId: 'avarewase.org.kensty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS4nl_HgYwWWnlh1rbQ7-LOT3cKI0tzks',
    appId: '1:151063543585:web:801f5aa9e51d1a92940860',
    messagingSenderId: '151063543585',
    projectId: 'kensty-8121f',
    authDomain: 'kensty-8121f.firebaseapp.com',
    storageBucket: 'kensty-8121f.firebasestorage.app',
    measurementId: 'G-JE4SF262K4',
  );
}
